2021-03-16 22:18:07,785 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 235, in wavelet_analysis
    wave()
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 252, in wave
    signal_power = cwt.wavelet_windows(signal, True)
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\wavelet_freq.py", line 115, in wavelet_windows
    trials = np.size(signal, 1)
  File "<__array_function__ internals>", line 5, in size
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\numpy\core\fromnumeric.py", line 3159, in size
    return a.shape[axis]
IndexError: tuple index out of range
2021-03-16 22:18:07,791 ERROR logFile Exception occurred err:tuple index out of range
2021-03-18 00:17:05,272 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 248, in wavelet_analysis
    features = [np.float(x) for x in features]
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 248, in <listcomp>
    features = [np.float(x) for x in features]
ValueError: could not convert string to float: '['
2021-03-18 00:17:05,291 ERROR logFile Exception occurred err:could not convert string to float: '['
2021-03-18 00:18:53,903 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in wavelet_analysis
    features = [np.float(x) for x in features]
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in <listcomp>
    features = [np.float(x) for x in features]
ValueError: could not convert string to float: '['
2021-03-18 00:18:53,905 ERROR logFile Exception occurred err:could not convert string to float: '['
2021-03-18 01:18:47,383 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in wavelet_analysis
    freqs = np.array(list(map(lambda x: np.float(x), features)))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in <lambda>
    freqs = np.array(list(map(lambda x: np.float(x), features)))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:18:47,386 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:19:29,450 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in wavelet_analysis
    freqs = np.array(list(map(lambda x: np.float(x), features)))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in <lambda>
    freqs = np.array(list(map(lambda x: np.float(x), features)))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:19:29,451 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:20:42,125 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in wavelet_analysis
    freqs = list(map(lambda x: np.float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in <lambda>
    freqs = list(map(lambda x: np.float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:20:42,128 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:22:10,929 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 249, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:22:10,932 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:25:23,684 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 250, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 250, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:25:23,687 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:26:58,794 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 250, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 250, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'"
2021-03-18 01:26:58,797 ERROR logFile Exception occurred err:could not convert string to float: "'"
2021-03-18 01:30:26,201 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:30:26,203 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:31:20,782 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 252, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 252, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:31:20,785 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:32:04,638 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 252, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 252, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:32:04,639 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:35:42,500 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:35:42,502 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:39:44,759 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'1'"
2021-03-18 01:39:44,760 ERROR logFile Exception occurred err:could not convert string to float: "'1'"
2021-03-18 01:40:53,150 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "['1'"
2021-03-18 01:40:53,152 ERROR logFile Exception occurred err:could not convert string to float: "['1'"
2021-03-18 01:41:41,230 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'"
2021-03-18 01:41:41,232 ERROR logFile Exception occurred err:could not convert string to float: "'"
2021-03-18 01:45:25,056 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: "'"
2021-03-18 01:45:25,059 ERROR logFile Exception occurred err:could not convert string to float: "'"
2021-03-18 01:46:20,152 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in wavelet_analysis
    freqs = list(map(lambda x: float(x), features))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 251, in <lambda>
    freqs = list(map(lambda x: float(x), features))
ValueError: could not convert string to float: '.'
2021-03-18 01:46:20,153 ERROR logFile Exception occurred err:could not convert string to float: '.'
2021-03-18 04:49:09,132 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 243, in show_signal
    return render_template("wavelet.html", features=features)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\templates\wavelet.html", line 41, in top-level template code
    <form method="POST" action="{{url_for('wavelet_analysis',features=features)}}">
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2177, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2054, in _partial_build
    rv = self._partial_build(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2067, in _partial_build
    rv = rule.build(values, append_unknown)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 1038, in build
    return self._build_unknown(**values)
  File "<werkzeug routing>", line 1, in <builder:'/wavelet_analysis/<int:features>'>
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 1257, in to_url
    value = self.num_convert(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
2021-03-18 04:49:09,227 ERROR logFile Exception occurred err:int() argument must be a string, a bytes-like object or a number, not 'list'
2021-03-18 04:49:21,571 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 243, in show_signal
    return render_template("wavelet.html", features=features)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\templates\wavelet.html", line 41, in top-level template code
    <form method="POST" action="{{url_for('wavelet_analysis',features=features)}}">
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2177, in build
    rv = self._partial_build(endpoint, values, method, append_unknown)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2054, in _partial_build
    rv = self._partial_build(
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 2067, in _partial_build
    rv = rule.build(values, append_unknown)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 1038, in build
    return self._build_unknown(**values)
  File "<werkzeug routing>", line 1, in <builder:'/wavelet_analysis/<int:features>'>
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\werkzeug\routing.py", line 1257, in to_url
    value = self.num_convert(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'
2021-03-18 04:49:21,574 ERROR logFile Exception occurred err:int() argument must be a string, a bytes-like object or a number, not 'list'
2021-03-18 04:50:41,282 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 258, in wavelet_analysis
    freqs = np.array(list(map(lambda x: np.float(x), features)))
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 258, in <lambda>
    freqs = np.array(list(map(lambda x: np.float(x), features)))
ValueError: could not convert string to float: ' 1. 50.'
2021-03-18 04:50:41,283 ERROR logFile Exception occurred err:could not convert string to float: ' 1. 50.'
2021-03-20 02:24:47,743 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 160, in show_post
    return render_template("layout.html", post=requested_post)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\jmat\.virtualenvs\flask05-b-tteyow\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\templates\layout.html", line 160, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2021-03-20 02:24:47,823 ERROR logFile Exception occurred err:Unexpected end of template. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
