2021-02-15 19:03:13,857 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 159, in save
    uploaded_file = request.files['file']
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\werkzeug\datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-02-15 19:03:13,888 ERROR logFile Exception occurred err:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-02-15 19:06:30,270 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 159, in save
    uploaded_file = request.files['file']
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\werkzeug\datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-02-15 19:06:30,273 ERROR logFile Exception occurred err:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-02-15 19:06:45,023 ERROR logFile Exception occurred exc: 
Traceback (most recent call last):
  File "C:\Users\JMAT\PycharmProjects\Flask05\app\main.py", line 159, in save
    uploaded_file = request.files['file']
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\flask\debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "C:\Users\JMAT\.virtualenvs\Flask05-b-tTEyOw\lib\site-packages\werkzeug\datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-02-15 19:06:45,026 ERROR logFile Exception occurred err:400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
